---
- hosts: fedora
  become: true
  tasks:
    - name: update repo index
      dnf:
        update_cache: yes
    - name: install fish package
      dnf:
        name: fish
        state: latest
    - name: install kitty package
      dnf:
        name: kitty
        state: latest

- hosts: ubuntu
  become: true
  tasks:
    - name: update repo index
      apt:
        update_cache: yes
    - name: install fish package
      apt:
        name: fish
        state: latest
    - name: install kitty package
      apt:
        name: kitty
        state: latest
